#!/usr/bin/env python3
"""Exercise the SSH wrapper with real Dropbear and a RAM-only recording dialer.

No network connection, account enrollment, or SSH-key changes are needed.
"""
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile

source = Path(sys.argv[1]).read_text()
dialer = "/home/root/.local/bin/tailscale"
assert source.count(dialer) == 1
with tempfile.TemporaryDirectory(prefix="inkline-proxy-check-", dir="/tmp") as directory:
    directory = Path(directory)
    recorder = directory / "dialer"
    # Paths are generated by tempfile; the recorder receives the actual argv
    # after Dropbear has invoked the proxy through /bin/sh.
    recorder.write_text("#!/bin/sh\nprintf '%s\\n' \"$@\" > \"$INKLINE_PROXY_TEST_ARGUMENTS\"\nexit 1\n")
    recorder.chmod(0o700)
    wrapper = directory / "tailscale-ssh"
    wrapper.write_text(source.replace(dialer, str(recorder)))
    wrapper.chmod(0o700)
    captured = directory / "arguments"
    env = dict(os.environ, INKLINE_PROXY_TEST_ARGUMENTS=str(captured))
    cases = [
        (["-p", "2200", "alice@host.ts.net", "git-upload-pack 'a repo.git'"], ["nc", "host.ts.net", "2200"]),
        (["-o", "Port=2022", "root@[fd7a:115c:a1e0::1]"], ["nc", "fd7a:115c:a1e0::1", "2022"]),
        (["bob@host/2222"], ["nc", "host", "2222"]),
    ]
    for args, expected in cases:
        captured.unlink(missing_ok=True)
        result = subprocess.run([str(wrapper), *args], env=env, capture_output=True, timeout=10)
        assert result.returncode != 0, "The recording dialer deliberately fails"
        assert captured.exists(), (args, result.stderr.decode(errors="replace"))
        assert captured.read_text().splitlines() == expected, (args, captured.read_text())
        print("Dropbear proxy destination passed:", json.dumps(expected), flush=True)
    result = subprocess.run([str(wrapper), "-G", "-p2200", "-i", "/tmp/key with spaces", "user@host"],
                            env=env, capture_output=True, text=True, timeout=10, check=True)
    assert result.stdout == "hostname host\nport 2200\n"
    captured.unlink()
    result = subprocess.run([str(wrapper), "-p", "0", "user@host"], env=env, capture_output=True, timeout=10)
    assert result.returncode != 0 and not captured.exists()
    print("Git configuration probe and invalid-port rejection passed.")
