;;; tests.el --- Integration checks run on the tablet, entirely in /tmp -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'latex)

(defun inkline-tex-test-command (name)
  (let ((buffer (current-buffer)) process)
    (save-current-buffer
      (setq process (TeX-command name #'TeX-master-file -1)))
    (let ((deadline (+ (float-time) 120)))
      (while (and (process-live-p process) (< (float-time) deadline))
        (accept-process-output process 0.1)))
    (when (process-live-p process) (delete-process process) (error "TeX timed out"))
    (unless (= (process-exit-status process) 0)
      (error "%s failed: %s" name (with-current-buffer (process-buffer process) (buffer-string))))
    (set-buffer buffer)))

(ert-deftest inkline-tex-real-builds-stay-in-ram ()
  (let* ((stage (make-temp-file "/tmp/inkline-tex-test-" t))
         (source (expand-file-name "source with spaces/" stage))
         (paper (expand-file-name "paper.tex" source))
         (default-directory stage)
         (TeX-after-compilation-finished-functions nil)
         buffer)
    (unwind-protect
        (progn
          (make-directory source t)
          (with-temp-file (expand-file-name "references.bib" source)
            (insert "@book{knuth,author={Donald Knuth},title={The TeXbook},year={1984},publisher={Addison Wesley}}\n"))
          (with-temp-file paper
            (insert "\\documentclass{article}\n\\begin{document}\nInkline RAM build. See \\cite{knuth}.\n\\newpage Second page.\n\\bibliographystyle{plain}\n\\bibliography{references}\n\\end{document}\n"))
          (setq buffer (find-file-noselect paper))
          (with-current-buffer buffer
            (LaTeX-mode)
            (setq TeX-master t TeX-PDF-mode t TeX-save-query nil)
            (should (derived-mode-p 'latex-mode))
            (should (equal (expand-file-name (TeX-master-file t)) paper))
            (let ((ram (inkline-ghostty-tex-build-directory)))
              (should (string-prefix-p "/tmp/" ram))
              (inkline-tex-test-command "LaTeX")
              (dolist (ext '("pdf" "aux" "log"))
                (should (file-readable-p (expand-file-name (concat "paper." ext) ram))))
              (should (equal (TeX-active-master "pdf") (expand-file-name "paper.pdf" ram)))
              (should (equal (ghostty-tex-output-file) (expand-file-name "paper.pdf" ram)))
              (inkline-tex-test-command "BibTeX")
              (should (file-readable-p (expand-file-name "paper.bbl" ram)))
              (inkline-tex-test-command "LaTeX")
              (inkline-tex-test-command "LaTeX")
              (should (equal (directory-files source nil "^[^.]") '("paper.tex" "references.bib")))
              (inkline-ghostty-tex-save-pdf (expand-file-name "saved.pdf" stage))
              (should (file-readable-p (expand-file-name "saved.pdf" stage)))
              (setq TeX-PDF-mode nil)
              (inkline-tex-test-command "LaTeX")
              (should (file-readable-p (expand-file-name "paper.dvi" ram)))
              (should (= 0 (call-process doc-view-dvipdfm-program nil "*dvipdfmx-test*" nil
                                        "-o" (expand-file-name "from-dvi.pdf" ram)
                                        (expand-file-name "paper.dvi" ram))))
              (should (equal (directory-files source nil "^[^.]") '("paper.tex" "references.bib")))
              (should (string-prefix-p "/tmp/" (make-auto-save-file-name))))))
      (when (buffer-live-p buffer) (kill-buffer buffer))
      (delete-directory stage t))))

(ert-deftest inkline-tex-distinct-documents-have-distinct-builds ()
  (let ((stage (make-temp-file "/tmp/inkline-tex-names-" t)) buffers directories)
    (unwind-protect
        (progn
          (dolist (name '("one" "two"))
            (let* ((path (expand-file-name (concat name "/paper.tex") stage)))
              (make-directory (file-name-directory path) t)
              (with-temp-file path (insert "\\documentclass{article}\n"))
              (let ((buffer (find-file-noselect path)))
                (push buffer buffers)
                (with-current-buffer buffer
                  (LaTeX-mode) (setq TeX-master t)
                  (push (inkline-ghostty-tex-build-directory) directories)))))
          (should-not (equal (car directories) (cadr directories))))
      (mapc #'kill-buffer buffers)
      (delete-directory stage t))))

(ert-deftest inkline-tex-init-blocks-preserve-personal-settings ()
  (let* ((stage (make-temp-file "/tmp/inkline-tex-config-" t))
         (root (expand-file-name "utility/releases/test/" stage))
         (config (expand-file-name "config/" stage))
         (init (expand-file-name "init.el" config))
         (original ";; My settings\n(setq my-private-preference 17)\n")
         (process-environment (copy-sequence process-environment)))
    (unwind-protect
        (progn
          (make-directory root t) (make-directory config t)
          (with-temp-file init (insert original))
          (setenv "INKLINE_GHOSTTY_TEX_ROOT" root)
          (setenv "INKLINE_GHOSTTY_TEX_EMACS_DIRECTORY" config)
          (cl-labels ((configure (action)
                        (setenv "INKLINE_GHOSTTY_TEX_ACTION" action)
                        (call-process "/home/root/.local/bin/emacs" nil "*config-test*" nil
                                      "-Q" "--batch" "-l"
                                      (expand-file-name "configure.el" inkline-ghostty-tex-root)))
                      (contents () (with-temp-buffer (insert-file-contents init) (buffer-string))))
            (should (= 0 (configure "--check")))
            (should (equal original (contents)))
            (should (= 0 (configure "--enable")))
            (should (string-prefix-p original (contents)))
            (should (file-readable-p (concat init ".before-inkline-ghostty-tex")))
            (let ((mtime (file-attribute-modification-time (file-attributes init))))
              (should (= 0 (configure "--enable")))
              (should (equal mtime (file-attribute-modification-time (file-attributes init)))))
            (should (= 0 (configure "--disable")))
            (should (equal original (contents)))
            (with-temp-file init (insert original ";; BEGIN Inkline ghostty-tex\n"))
            (let ((invalid (contents)))
              (should-not (= 0 (configure "--enable")))
              (should (equal invalid (contents))))))
      (delete-directory stage t))))

(ert-run-tests-batch-and-exit)
