# Embed the shipped notices so Settings works offline, even if someone moves
# the executable. Keep the original plain-text files in release/source bundles.
file(READ "${PROJECT_SOURCE_DIR}/licenses/catalog.json" _legal_catalog)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/licenses/catalog.json")
string(JSON _legal_count LENGTH "${_legal_catalog}")
math(EXPR _legal_last "${_legal_count} - 1")
set(INKLINE_LEGAL_ENTRIES "")
foreach(_index RANGE ${_legal_last})
    string(JSON _title GET "${_legal_catalog}" ${_index} title)
    string(JSON _file_count LENGTH "${_legal_catalog}" ${_index} files)
    math(EXPR _file_last "${_file_count} - 1")
    set(_body "")
    foreach(_file_index RANGE ${_file_last})
        string(JSON _path GET "${_legal_catalog}" ${_index} files ${_file_index})
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/${_path}")
        file(READ "${PROJECT_SOURCE_DIR}/${_path}" _text)
        string(APPEND _body "${_text}\n\n")
    endforeach()
    string(FIND "${_title}${_body}" ")INKLINE_LEGAL\"" _delimiter)
    if(NOT _delimiter EQUAL -1)
        message(FATAL_ERROR "License text conflicts with the C++ raw-string delimiter")
    endif()
    string(APPEND INKLINE_LEGAL_ENTRIES "{R\"INKLINE_LEGAL(${_title})INKLINE_LEGAL\", R\"INKLINE_LEGAL(${_body})INKLINE_LEGAL\"},\n")
endforeach()
configure_file("${PROJECT_SOURCE_DIR}/cmake/legal_text.hpp.in" "${CMAKE_CURRENT_BINARY_DIR}/generated/legal_text.hpp" @ONLY)
