set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR armv7)
get_filename_component(_rmt_project "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(RMT_SYSROOT "${_rmt_project}/.cache/sdk/sysroot-5.7.119" CACHE PATH "Extracted reMarkable target sysroot")
if(NOT EXISTS "${RMT_SYSROOT}/rmt-sysroot.json")
    message(FATAL_ERROR "Run scripts/extract-sdk-sysroot.py before cross-compiling")
endif()

find_program(_rmt_zig zig REQUIRED)
execute_process(COMMAND "${_rmt_zig}" env OUTPUT_VARIABLE _rmt_zig_env COMMAND_ERROR_IS_FATAL ANY)
string(REGEX MATCH "[.]lib_dir = \"([^\"]+)\"" _rmt_match "${_rmt_zig_env}")
set(_rmt_zig_include "${CMAKE_MATCH_1}/include")
if(NOT EXISTS "${_rmt_zig_include}/stddef.h")
    message(FATAL_ERROR "Could not find Zig's compiler headers")
endif()
set(CMAKE_C_COMPILER "${_rmt_zig}")
set(CMAKE_C_COMPILER_ARG1 cc)
set(CMAKE_CXX_COMPILER "${_rmt_zig}")
set(CMAKE_CXX_COMPILER_ARG1 c++)
set(CMAKE_AR "${_rmt_project}/scripts/zig-ar.sh")
set(CMAKE_RANLIB "${_rmt_project}/scripts/zig-ranlib.sh")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_SYSROOT "${RMT_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH "${RMT_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_SKIP_RPATH TRUE)

set(_rmt_target "-target arm-linux.5.4-gnueabihf.2.39 -mcpu=cortex_a7")
set(CMAKE_C_FLAGS_INIT "${_rmt_target} -nostdinc -isystem ${_rmt_zig_include} -isystem ${RMT_SYSROOT}/usr/include")
file(GLOB _rmt_cxx_headers LIST_DIRECTORIES TRUE "${RMT_SYSROOT}/usr/include/c++/*")
list(GET _rmt_cxx_headers 0 _rmt_cxx)
# Use the SDK's libstdc++ ABI, also used by the tablet's Qt libraries.
set(CMAKE_CXX_FLAGS_INIT "${_rmt_target} -nostdinc -nostdinc++ -nostdlib++ -isystem ${_rmt_cxx} -isystem ${_rmt_cxx}/arm-remarkable-linux-gnueabi -isystem ${_rmt_cxx}/backward -isystem ${_rmt_zig_include} -isystem ${RMT_SYSROOT}/usr/include")
# Zig treats -lstdc++ as a request for its bundled libc++; full filenames keep
# the SDK's GNU C++ runtime selected. Zig applies --sysroot to -L paths itself.
set(CMAKE_CXX_STANDARD_LIBRARIES_INIT "${RMT_SYSROOT}/usr/lib/libstdc++.so ${RMT_SYSROOT}/usr/lib/libgcc_s.so.1")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-L/usr/lib")
set(RMT_ZIG_TARGET arm-linux.5.4-gnueabihf CACHE STRING "" FORCE)
set(RMT_ZIG_CPU cortex_a7 CACHE STRING "" FORCE)
set(ENV{PKG_CONFIG_SYSROOT_DIR} "${RMT_SYSROOT}")
set(ENV{PKG_CONFIG_LIBDIR} "${RMT_SYSROOT}/usr/lib/pkgconfig")
set(ENV{PKG_CONFIG_PATH} "")
set(ENV{ZIG_GLOBAL_CACHE_DIR} "${_rmt_project}/.cache/zig-global")
